In [1]:
import numpy as np

In [2]:
d = np.load("demand.npy")
a = np.load("assignments.npy")


In [3]:
d[3]

array([[ 0,  0,  0,  0,  0,  7,  7,  7,  0,  0,  0,  0],
       [ 4,  4,  4,  0,  0,  0,  0,  0, 12, 12,  8,  0],
       [ 0,  2,  2,  0,  0,  6,  8,  6, 12, 12, 10,  0],
       [ 3,  3,  3,  0,  0,  0,  0,  0,  6,  8,  6,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [4]:
a[:, 0, :, :].sum(0) - d[3]

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-2.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -2., -2.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [5]:
a[:, 0, :, :].sum((1, 2))

array([3., 1., 1., 3., 2., 4., 4., 1., 1., 4., 2., 2., 4., 4., 4., 2., 2.,
       1., 3., 4., 1., 4., 3., 3., 4., 2., 3., 4., 2., 1., 4., 0., 2., 2.,
       3., 3., 3., 3., 4., 4., 4., 3., 3., 4., 4., 4., 4., 3., 3., 3., 3.])

In [6]:
a[:, 0, :, :].sum((1, 2))[31]

0.0

In [7]:
a[:, 0, :, :][31]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])