In [123]:
import numpy as np

In [124]:
a = np.load("assignments.npy")
d = np.load("demand.npy")

In [125]:
a[:, 0, :, :].shape

(22, 5, 12)

In [126]:
np.save("week5_assignments.npy", a[:, 0,:,:])

In [127]:
a[:, 0, :, :].sum()

96.0

In [128]:
a[:, 0, :, :].sum((1, 2))

array([3., 5., 5., 5., 5., 5., 5., 5., 5., 4., 5., 3., 4., 5., 3., 4., 5.,
       4., 3., 3., 5., 5.])

In [129]:
d[4, :, :] - a[:, 0, :, :].sum(0)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 2., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [122]:
d[4, :, :]

array([[0, 0, 0, 0, 0, 6, 6, 6, 0, 3, 3, 0],
       [0, 0, 0, 0, 3, 3, 3, 4, 5, 4, 3, 3],
       [0, 0, 0, 0, 3, 3, 3, 2, 2, 0, 0, 0],
       [0, 0, 0, 0, 3, 3, 4, 5, 4, 0, 3, 3],
       [0, 0, 0, 0, 3, 3, 3, 0, 0, 0, 0, 0]])

In [107]:
a[:, 0, :, :].sum(0)

array([[0., 0., 0., 0., 0., 6., 6., 6., 0., 2., 1., 0.],
       [0., 0., 0., 0., 3., 3., 3., 4., 5., 4., 3., 3.],
       [0., 0., 0., 0., 3., 3., 3., 2., 2., 0., 0., 0.],
       [0., 0., 0., 0., 3., 3., 4., 5., 4., 0., 3., 3.],
       [0., 0., 0., 0., 3., 3., 3., 0., 0., 0., 0., 0.]])

In [108]:
d[4, :, :]

array([[0, 0, 0, 0, 0, 6, 6, 6, 0, 3, 3, 0],
       [0, 0, 0, 0, 3, 3, 3, 4, 5, 4, 3, 3],
       [0, 0, 0, 0, 3, 3, 3, 2, 2, 0, 0, 0],
       [0, 0, 0, 0, 3, 3, 4, 5, 4, 0, 3, 3],
       [0, 0, 0, 0, 3, 3, 3, 0, 0, 0, 0, 0]])

In [18]:
d[4, :, :]

array([[0, 0, 0, 0, 0, 6, 6, 6, 0, 3, 3, 0],
       [0, 0, 0, 0, 3, 3, 3, 4, 5, 4, 3, 3],
       [0, 0, 0, 0, 3, 3, 3, 2, 2, 0, 0, 0],
       [0, 0, 0, 0, 3, 3, 4, 5, 4, 0, 3, 3],
       [0, 0, 0, 0, 3, 3, 3, 0, 0, 0, 0, 0]])

In [15]:
a.sum(0) - d[4, :, :]

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -1., -2.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [78]:
a.sum((2, 3))

array([[ 3.,  2.,  2.,  1.,  3.],
       [ 3.,  9.,  4.,  5.,  6.],
       [ 5.,  9.,  7.,  5.,  5.],
       [ 1.,  2.,  3.,  3.,  0.],
       [ 4.,  5.,  6.,  8.,  5.],
       [ 4.,  4.,  6.,  4.,  4.],
       [ 4., 10.,  8.,  9.,  7.],
       [ 3., 10.,  6.,  8.,  5.],
       [ 4.,  4.,  4.,  4.,  5.],
       [ 3.,  5.,  4.,  5.,  5.],
       [ 4., 10., 10.,  6.,  8.],
       [ 2.,  2.,  2.,  2.,  0.],
       [ 4.,  4.,  4.,  4.,  3.],
       [ 3.,  3.,  5.,  6.,  4.],
       [ 3.,  4.,  4.,  4.,  2.],
       [ 2.,  4.,  3.,  4.,  0.],
       [ 2.,  4.,  3.,  3.,  3.],
       [ 5.,  4.,  4.,  4.,  2.],
       [ 2.,  3.,  4.,  3.,  3.],
       [ 2.,  2.,  3.,  3.,  2.],
       [ 2.,  4.,  3.,  4.,  3.],
       [ 2.,  5.,  5.,  6.,  2.]])