In [1]:
import numpy as np

In [4]:
d = np.load("demand.npy")
a = np.load("assignments.npy")


In [5]:
d[7]

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 2, 4, 4, 3, 2, 2, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 3, 2, 2, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [7]:
a[:, 0, :, :].sum(0) - d[7]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [9]:
a[:, 0, :, :].sum((1, 2))

array([4., 4., 4., 3., 3., 4., 2.])

In [11]:
d[7].sum()

24