In [1]:
import numpy as np

In [2]:
d = np.load("demand.npy")
a = np.load("assignments.npy")


In [4]:
d[9]

array([[0, 0, 0, 0, 0, 0, 4, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 0, 0],
       [0, 0, 0, 0, 0, 2, 3, 3, 3, 2, 2, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 3, 2, 2, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [6]:
a[:, 0, :, :].sum(0) - d[10]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [7]:
a[:, 0, :, :].sum((1, 2))

array([4., 4., 4., 2., 3., 4., 3.])