In [16]:
import numpy as np

In [17]:
a = np.load("assignments.npy")
d = np.load("demand.npy")
av = np.load("availabiltiies.npy")

In [18]:
a[:, 0, :, :].sum(0) - d[12]

array([[ 0.,  0.,  0.,  0.,  0.,  0., -1., -1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -2., -2.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [19]:
# convert all 5's to 0, everything else to 1s
av[av == 5] = 0

In [20]:
av[av != 0] = 1

In [21]:
av.sum(0)

array([[3, 2, 4, 4, 1, 4, 3, 3, 2, 1, 3, 2],
       [3, 4, 5, 1, 1, 1, 2, 2, 2, 2, 1, 1],
       [5, 3, 5, 4, 1, 5, 5, 5, 2, 2, 2, 2],
       [3, 3, 5, 2, 2, 2, 3, 3, 5, 5, 2, 1],
       [4, 2, 3, 3, 2, 3, 5, 4, 4, 4, 2, 2]])

In [22]:
a[:, 0, :, :].sum((1, 2))

array([4., 4., 6., 4., 4., 6., 3.])