In [46]:
import numpy as np

In [47]:
a = np.load("assignments.npy")
d = np.load("demand.npy")

In [48]:
d[3].sum()

67

In [49]:
a.sum(0) - d[3:]

array([[[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0

In [68]:
d.sum((1, 2))

array([  0,   0,   0,  67, 109, 100, 101,  78])

In [69]:
a.sum((2, 3))

array([[ 3.,  2.,  2.,  1.,  3.],
       [ 4.,  9.,  4.,  5.,  6.],
       [ 5.,  9.,  7.,  5.,  5.],
       [ 0.,  2.,  3.,  3.,  0.],
       [ 5.,  5.,  6.,  8.,  5.],
       [ 4.,  4.,  6.,  4.,  4.],
       [ 4., 10.,  8.,  9.,  7.],
       [ 4., 10.,  6.,  8.,  5.],
       [ 4.,  4.,  4.,  4.,  5.],
       [ 4.,  5.,  4.,  5.,  5.],
       [ 4., 10., 10.,  6.,  8.],
       [ 0.,  2.,  2.,  2.,  0.],
       [ 5.,  4.,  4.,  4.,  3.],
       [ 3.,  3.,  5.,  6.,  4.],
       [ 3.,  4.,  4.,  4.,  2.],
       [ 0.,  4.,  3.,  4.,  0.],
       [ 2.,  4.,  3.,  3.,  3.],
       [ 5.,  4.,  4.,  4.,  2.],
       [ 2.,  3.,  4.,  3.,  3.],
       [ 2.,  2.,  3.,  3.,  2.],
       [ 3.,  4.,  3.,  4.,  3.],
       [ 1.,  5.,  5.,  6.,  2.]])