In [1]:
import numpy as np

In [2]:
a = np.load("assignments.npy")
d = np.load("demand.npy")

In [3]:
a.sum()

306.0

In [4]:
d.sum()

343

In [16]:
[(a[:, x, :, :].sum(0) - d[x + 3]).sum() for x in range(10)]

[-1.0, 5.0, 5.0, -7.0, 4.0, -7.0, -7.0, 3.0, 5.0, -7.0]

In [17]:
d[4]

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 2, 3, 3, 2, 2, 2, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 3, 2, 2, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [18]:
a[:, 1, :, :].sum(0)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 4., 3., 3., 3., 3., 2., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 3., 3., 2., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [8]:
d[2]

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 2, 3, 3, 2, 2, 2, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 3, 2, 2, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [9]:
a[:, 0, :, :].sum(0) - d[2]

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  2.,  2.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  2.,  2.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -3., -2., -2.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [10]:
a.sum((1, 2, 3)) - [56, 56, 56, 56, 70, 56, 42]

array([-11., -14., -12., -15., -17.,  -8.,  -9.])