In [5]:
import numpy as np

In [6]:
d = np.load("demand.npy")
a = np.load("assignments.npy")


In [7]:
d[8]

array([[0, 0, 0, 0, 0, 0, 4, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 0, 0],
       [0, 0, 0, 0, 0, 2, 3, 3, 3, 2, 2, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 3, 2, 2, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [12]:
a[:, 0, :, :].sum(0) - d[9]

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -2., -2.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [9]:
a[:, 0, :, :].sum((1, 2))

array([6., 4., 5., 4., 4., 6., 5.])