In [1]:
import numpy as np

In [2]:
d = np.load("demand.npy")
a = np.load("assignments.npy")


In [3]:
d[3]

array([[0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0],
       [0, 0, 0, 0, 0, 3, 4, 4, 4, 3, 3, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [4]:
a[:, 0, :, :].sum(0) - d[3]

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0., -1., -1., -2., -2., -1., -2.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  3.,  2.,  2.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [5]:
a[:, 0, :, :].sum((1, 2))

array([4., 4., 4., 4., 4., 4., 3.])

In [6]:
a[:, 0, :, :][31]

IndexError: index 31 is out of bounds for axis 0 with size 7