In [1]:
import numpy as np

In [2]:
a = np.load("assignments.npy")
d = np.load("demand.npy")

In [3]:
a[:, 0, :, :].sum(0)

array([[0., 0., 0., 0., 0., 0., 0., 0., 4., 4., 2., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 3., 5., 5., 4., 4., 2.],
       [2., 3., 3., 0., 0., 0., 0., 0., 6., 6., 4., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [4]:
a[:, 0, :, :].sum(0) - d[1]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [5]:
a[:, 0, :, :].sum((1, 2))

array([2., 2., 5., 3., 2., 2., 2., 7., 8., 5., 2., 4., 5., 0., 0., 5., 3.,
       0.])

In [6]:
d[1]

array([[0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 2, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 5, 5, 4, 4, 2],
       [2, 3, 3, 0, 0, 0, 0, 0, 6, 6, 4, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [7]:
a[:, 0, :, :].sum((1, 2))

array([2., 2., 5., 3., 2., 2., 2., 7., 8., 5., 2., 4., 5., 0., 0., 5., 3.,
       0.])