In [18]:
import numpy as np

In [19]:
a = np.load("assignments.npy")
d = np.load("demand.npy")

In [20]:
a[:, 0, :, :].sum()

23.0

In [21]:
d[4].sum()

24

In [22]:
d[4] - a[:, 0, :, :].sum(0)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [23]:
a[:, 0, :, :].sum((1, 2))

array([4., 4., 4., 2., 3., 4., 2.])

In [24]:
a.sum((1, 2, 3))

array([41., 40., 40., 32., 43., 44., 28.])