In [73]:
import numpy as np

In [74]:
a = np.load("assignments.npy")
d = np.load("demand.npy")
av = np.load("availabiltiies.npy")

In [75]:
d[6] - a[:, 0, :, :].sum(0)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 2., 2., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [76]:
a[:, 0, :, :][:, 0, 6:8]

array([[ 1.,  0.],
       [ 0.,  0.],
       [-0.,  1.],
       [ 1.,  1.],
       [ 1.,  0.],
       [ 1.,  1.],
       [ 0.,  1.]])

In [77]:
a[5, 0, :, :]

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1., -0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [78]:
av[5]

array([[4, 5, 3, 3, 5, 1, 1, 1, 5, 5, 4, 5],
       [5, 5, 4, 5, 5, 5, 5, 1, 1, 3, 5, 5],
       [4, 5, 3, 3, 5, 1, 1, 1, 5, 5, 4, 5],
       [5, 5, 3, 5, 5, 5, 5, 1, 1, 3, 4, 5],
       [4, 5, 3, 3, 5, 1, 1, 1, 3, 4, 5, 5]])

In [79]:
a[:, 0, :, :][5]

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1., -0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [80]:
d[6]

array([[0, 0, 0, 0, 0, 0, 4, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 0, 0],
       [0, 0, 0, 0, 0, 2, 3, 3, 3, 2, 2, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 3, 2, 2, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [81]:
a[:, 0, :, :].sum((1, 2))

array([6., 4., 5., 4., 4., 6., 5.])