In [1]:
import numpy as np

In [2]:
a = np.load("assignments.npy")
d = np.load("demand.npy")

In [3]:
a[:, 0, :, :].sum(0)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [2., 4., 0., 0., 0., 0., 0., 6., 8., 8., 6., 0.],
       [0., 0., 0., 0., 0., 0., 4., 4., 8., 8., 6., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [4]:
d[3]

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 3,  4,  0,  0,  0,  0,  0,  8, 10, 10,  6,  0],
       [ 0,  0,  0,  0,  0,  0,  4,  4,  8,  8,  6,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [5]:
a[:, 0, :, :].sum((1, 2))

array([5., 5., 4., 3., 5., 1., 4., 3., 5., 4., 5., 1., 5., 2., 2., 5., 3.,
       0., 0., 2.])