In [1]:
import numpy as np

In [2]:
a = np.load("assignments.npy")
d = np.load("demand.npy")
av = np.load("availabiltiies.npy")

In [3]:
a[:, 0, :, :].sum(0) - d[11]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [4]:
a[:, 0, :, :].sum((1, 2))

array([4., 4., 4., 2., 3., 4., 3.])

In [5]:
av

array([[[5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 1, 1, 5, 1, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 1, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]],

       [[5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 1, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [2, 2, 2, 5, 5, 5, 4, 4, 1, 1, 5, 5],
        [5, 5, 5, 5, 5, 4, 4, 4, 1, 1, 5, 5],
        [1, 1, 1, 5, 5, 5, 4, 4, 1, 1, 5, 5]],

       [[3, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4],
        [5, 5, 4, 4, 4, 1, 1, 3, 5, 5, 4, 4],
        [1, 1, 5, 5, 5, 5, 5, 5, 1, 1, 1, 5],
        [5, 5, 5, 5, 4, 3, 3, 5, 5, 5, 3, 3],
        [4, 4, 5, 5, 5, 5, 3, 5, 5, 5, 5, 5]],

       [[5, 5, 5, 1, 1, 1, 1, 3, 5, 5, 5, 5],
        [3, 3, 3, 5, 5, 5, 3, 5, 5, 5, 5, 5],
        [5, 5, 5, 3, 5, 3, 3, 3, 5, 5, 5, 5],
        [3, 3, 3, 5, 5, 5, 3, 5, 5, 5, 5, 5],
        [5, 5, 5, 3, 3, 3, 3, 5, 5, 5, 5, 5]],

       [[4, 5, 1, 1, 5, 5, 4, 5, 3, 3, 4, 4],
        [5, 5, 4, 4, 1, 5,