In [1]:
import numpy as np

In [2]:
a = np.load("assignments.npy")
d = np.load("demand.npy")

In [3]:
a[:, 0, :, :].shape

(49, 5, 12)

In [4]:
d[2].sum()

108

In [5]:
d[2].shape

(5, 12)

In [18]:
a[:, 0, :, :].sum(0) - d[2]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [7]:
d[1] - a[:, 0, :, :].sum(0)

array([[ 0.,  2.,  0.,  0.,  0.,  3.,  3.,  3.,  3.,  5.,  5.,  0.],
       [ 0., -2.,  2.,  0.,  0., -4., -4., -4., -7., -7., -4.,  0.],
       [ 0.,  2.,  2.,  0.,  0.,  2.,  5.,  0.,  0., -2., -4.,  0.],
       [ 1., -1., -1.,  0.,  0.,  0.,  0.,  0., -1., -3., -1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [8]:
a[27][0]

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [9]:
a[:, 0, :, :].sum((1, 2))

array([2., 2., 0., 0., 3., 3., 3., 1., 1., 3., 1., 1., 3., 3., 3., 1., 0.,
       1., 3., 3., 1., 3., 3., 4., 3., 1., 3., 3., 1., 1., 3., 3., 1., 1.,
       2., 3., 2., 2., 3., 7., 3., 2., 2., 3., 3., 3., 3., 2., 0.])