In [5]:
import numpy as np

In [6]:
a = np.load("assignments.npy")
d = np.load("demand.npy")

In [7]:
a[:, 0, :, :].sum(0) - d[14]

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -1., -1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [8]:
a[:, 0, :, :].sum(0)

array([[0., 0., 0., 0., 0., 4., 4., 4., 6., 6., 6., 0.],
       [4., 4., 4., 0., 0., 0., 0., 0., 7., 7., 8., 0.],
       [0., 5., 5., 0., 0., 3., 3., 5., 8., 8., 5., 0.],
       [5., 5., 5., 0., 0., 0., 0., 0., 8., 8., 8., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [9]:
a[:, 0, :, :].sum((1, 2))

array([3., 2., 2., 3., 3., 3., 3., 1., 1., 3., 1., 1., 4., 4., 4., 1., 3.,
       1., 3., 3., 1., 3., 4., 3., 3., 2., 3., 4., 1., 1., 4., 3., 2., 1.,
       3., 4., 2., 3., 3., 4., 4., 2., 3., 4., 3., 4., 3., 4., 3., 3., 3.,
       3., 3.])