In [1]:
import numpy as np

In [2]:
a = np.load("assignments.npy")
d = np.load("demand.npy")

In [3]:
a[:, 0, :, :].sum(0) - d[15]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [4]:
a[:, 0, :, :].sum(0)

array([[0., 0., 0., 0., 0., 0., 0., 0., 2., 2., 2., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 2., 2., 2., 0.],
       [0., 0., 0., 0., 0., 0., 3., 3., 3., 2., 2., 0.],
       [2., 3., 0., 0., 0., 0., 0., 0., 3., 3., 2., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [5]:
a[:, 0, :, :].sum((1, 2))

array([0., 3., 5., 2., 4., 1., 0., 1., 0., 5., 1., 4., 5., 2., 2., 2., 0.,
       0., 0., 1.])