In [1]:
import numpy as np

In [2]:
a = np.load("assignments.npy")
d = np.load("demand.npy")

In [3]:
a[:, 0, :, :].shape

(34, 5, 12)

In [4]:
a[:, 0, :, :].sum()

96.0

In [5]:
d.shape

(16, 5, 12)

In [6]:
d[1] - a[:, 0, :, :].sum(0)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [2., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [7]:
a[27][0]

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0., -0.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [13]:
a[:, 0, :, :].sum((1, 2))

array([3., 3., 4., 4., 1., 1., 4., 2., 2., 4., 3., 4., 2., 3., 2., 4., 4.,
       1., 4., 3., 4., 4., 2., 2., 4., 2., 1., 4., 3., 2., 2., 3., 2., 3.])