In [16]:
import numpy as np

In [17]:
a = np.load("assignments.npy")
d = np.load("demand.npy")

In [18]:
a[:, 0, :, :].sum(0)

array([[0., 0., 0., 0., 0., 0., 0., 0., 2., 2., 2., 0.],
       [2., 2., 0., 0., 0., 0., 0., 2., 3., 3., 2., 0.],
       [0., 0., 0., 0., 0., 0., 3., 4., 4., 4., 3., 0.],
       [2., 3., 3., 0., 0., 0., 0., 0., 6., 6., 4., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [19]:
d[4] - a[:, 0, :, :].sum(0)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [20]:
a[:, 0, :, :].sum((1, 2))

array([5., 4., 4., 3., 3., 4., 3., 3., 1., 6., 1., 3., 5., 3., 2., 3., 5.,
       0., 0., 4.])