In [1]:
import numpy as np

In [2]:
a = np.load("assignments.npy")
d = np.load("demand.npy")

In [3]:
a[:, 0, :, :].sum(0)

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 2.,  2.,  0.,  0.,  0.,  0.,  0.,  2.,  3.,  3.,  2.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  5.,  6.,  6.,  4.,  3.,  0.],
       [ 3.,  5.,  5.,  0.,  0.,  0.,  0.,  0., 10., 10.,  8.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [4]:
a[:, 0, :, :].sum(0) - d[5]

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -2.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [5]:
a[:, 0, :, :].sum((1, 2))

array([5., 5., 5., 3., 5., 2., 5., 1., 5., 6., 6., 5., 5., 3., 2., 4., 5.,
       2., 0., 5.])