In [15]:
import numpy as np

In [16]:
a = np.load("assignments.npy")
d = np.load("demand.npy")

In [17]:
a[:, 0, :, :].sum(0) - d[14]

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -3., -3., -3.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -1., -2.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [18]:
a[:, 0, :, :].sum(0)

array([[0., 0., 0., 0., 0., 0., 0., 0., 9., 9., 7., 0.],
       [3., 4., 0., 0., 0., 0., 0., 6., 8., 7., 4., 0.],
       [0., 0., 0., 0., 0., 0., 3., 3., 4., 4., 3., 0.],
       [2., 2., 3., 0., 0., 0., 0., 0., 4., 4., 2., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [19]:
a[:, 0, :, :].sum((1, 2))

array([5., 6., 5., 4., 6., 4., 6., 6., 5., 7., 6., 5., 6., 5., 3., 4., 5.,
       1., 1., 1.])