In [11]:
import numpy as np

In [12]:
a = np.load("assignments.npy")
d = np.load("demand.npy")

In [13]:
a[:, 0, :, :].sum(0) - d[13]

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -3., -3., -3.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -1., -2., -3.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0., -3., -2., -3., -3., -3.,  0.],
       [ 0., -1.,  0.,  0.,  0.,  0.,  0.,  0., -3., -3., -3.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [14]:
a[:, 0, :, :].sum(0)

array([[0., 0., 0., 0., 0., 0., 0., 0., 5., 5., 5., 0.],
       [4., 4., 0., 0., 0., 0., 0., 6., 5., 4., 3., 0.],
       [0., 0., 0., 0., 0., 0., 3., 6., 5., 5., 3., 0.],
       [4., 5., 6., 0., 0., 0., 0., 0., 9., 9., 7., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [15]:
a[:, 0, :, :].sum((1, 2))

array([5., 6., 5., 4., 6., 6., 6., 8., 8., 7., 7., 6., 6., 5., 3., 4., 5.,
       1., 1., 4.])